/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

// Reduce the size of the library by disabling some features
//#define LOTTIE_CACHE_SUPPORT 1

// This seems cause issue https://github.com/Samsung/rlottie/issues/518
//#define LOTTIE_THREAD_SUPPORT 1
